DROP TABLE IF EXISTS track;


CREATE TABLE track (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  artist TEXT NOT NULL UNIQUE ,
  genre TEXT NOT NULL,
  track_length INTEGER NOT NULL
);
